<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net9.0</TargetFramework>
    <UseAppHost>false</UseAppHost>
    <Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
    <JellyfinInstallDir>$(MSBuildThisFileDirectory)../artifacts/server-reference/usr/lib/jellyfin</JellyfinInstallDir>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../FinampLyrics/FinampLyrics.csproj" />
    <Reference Include="MediaBrowser.Controller"><HintPath>$(JellyfinInstallDir)/MediaBrowser.Controller.dll</HintPath></Reference>
    <Reference Include="MediaBrowser.Common"><HintPath>$(JellyfinInstallDir)/MediaBrowser.Common.dll</HintPath></Reference>
    <Reference Include="MediaBrowser.Model"><HintPath>$(JellyfinInstallDir)/MediaBrowser.Model.dll</HintPath></Reference>
    <Reference Include="Jellyfin.Data"><HintPath>$(JellyfinInstallDir)/Jellyfin.Data.dll</HintPath></Reference>
  </ItemGroup>
</Project>
